# fly.toml app configuration file generated for savy-fso-pokedex on 2023-06-06T18:11:37+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "savy-fso-pokedex"
primary_region = "sin"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [[http_service.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[http_service.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/health"
    protocol = "http"
  
  [[http_service.script_checks]]
    command       = "/path/to/your/script"
    args          = ["a", "b", "c"]
    grace_period  = "1s"
    interval      = "5s"
    restart_limit = 0
    timeout       = "1s"
