name: Health Check!

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  url-health-checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed app url
        uses: jtalk/url-health-check-action@v3
        with: 
          url: https://savy-fso-pokedex.fly.dev/
          max-attempts: 2
          retry-delay: 7s